# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-22 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interstorm_wheel', '0002_wheelaccess_wheelaccesslog_wheelbonuscode_wheelgames_wheelimagelevel_wheelpercentage_wheeltransactio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheelaccess',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='wheelaccesslog',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='wheelbonuscode',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='wheelgames',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='wheelimagelevel',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='wheelpercentage',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='wheeltransaction',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
